/**
 * Pull live leaderboard from Neon (DATABASE_URL) and generate Remotion data.
 *
 * Run from repo root with DB URL (Vercel / Neon env or local .env.local):
 *
 *   pnpm remotion:bake-data
 *
 * Optional: REMOTION_LEADERBOARD_PERIOD=week|month|alltime|today (default: week)
 *
 * Writes: remotion/src/video-leaderboard.generated.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import type { LeaderboardPeriod } from '../src/contracts/clawrank-domain';
import { getLeaderboardData } from '../src/lib/clawrank-data';

const ROOT = path.join(__dirname, '..');
const OUT_FILE = path.join(ROOT, 'remotion', 'src', 'video-leaderboard.generated.ts');

/** Typical git worktree: repo/.claude/worktrees/<name> → app root is ../../../ */
const ENV_FALLBACKS = [
  path.join(ROOT, '.env.local'),
  path.join(ROOT, '..', '..', '..', '.env.local'),
];

function parseEnvFile(filePath: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!fs.existsSync(filePath)) return out;
  const text = fs.readFileSync(filePath, 'utf8');
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/** Later paths override earlier; shell env wins and is never replaced. */
function loadEnvLocal(): void {
  const merged: Record<string, string> = {};
  for (const p of ENV_FALLBACKS) {
    Object.assign(merged, parseEnvFile(p));
  }
  for (const [key, val] of Object.entries(merged)) {
    if (process.env[key] === undefined) {
      process.env[key] = val;
    }
  }
}

function periodFromEnv(): LeaderboardPeriod {
  const p = (process.env.REMOTION_LEADERBOARD_PERIOD || 'week').toLowerCase();
  if (p === 'today' || p === 'week' || p === 'month' || p === 'alltime') {
    return p;
  }
  console.warn(
    `Unknown REMOTION_LEADERBOARD_PERIOD="${p}", using "week"`,
  );
  return 'week';
}

async function main(): Promise<void> {
  loadEnvLocal();

  if (!process.env.DATABASE_URL) {
    console.error(
      'DATABASE_URL is not set. Add it to .env.local or export it (Neon / Vercel env).',
    );
    process.exit(1);
  }

  const period = periodFromEnv();

  const data = await getLeaderboardData('live', period);

  if (!data.rows.length) {
    console.error(
      'Leaderboard query returned 0 rows. Check DB data and period filter.',
    );
    process.exit(1);
  }

  const rowsJson = JSON.stringify(data.rows, null, '\t');
  const ts = `/* eslint-disable */
/** Generated by scripts/bake-remotion-video-data.ts — do not edit */
import type { LeaderboardRow } from './types';

export const BAKED_VIDEO_ROWS: LeaderboardRow[] = ${rowsJson};
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, ts, 'utf8');

  console.log(
    `Wrote ${OUT_FILE} (${data.rows.length} rows, period=${period}, label=${data.periodLabel})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
