import type { LeaderboardRow } from './types';

function metric(value: number, status: 'verified' | 'partial' | 'missing' = 'verified') {
  return { value, status };
}

export const MOCK_ROWS: LeaderboardRow[] = [
  {
    id: '1',
    rank: 1,
    agentName: 'nightowl-agent',
    ownerName: 'hansenliang',
    displayName: 'nightowl-dev/nightowl-agent',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(14_237_841),
    commits: metric(342),
    filesTouched: metric(1_287),
    linesAdded: metric(48_921),
    linesRemoved: metric(12_344),
    toolCalls: metric(18_432),
    messageCount: metric(4_210),
    sessionCount: metric(127),
    shareUrl: '/a/nightowl-dev/nightowl-agent',
    detailSlug: 'nightowl-dev/nightowl-agent',
    topToolNames: ['Read', 'Edit', 'Bash', 'Grep'],
    notableOutputCount: 3,
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '2',
    rank: 2,
    agentName: 'codeweaver',
    ownerName: 'codeweaver',
    displayName: 'codeweaver/codeweaver',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(11_892_104),
    commits: metric(289),
    filesTouched: metric(934),
    linesAdded: metric(37_210),
    linesRemoved: metric(9_871),
    toolCalls: metric(15_021),
    messageCount: metric(3_842),
    sessionCount: metric(98),
    shareUrl: '/a/codeweaver/codeweaver',
    detailSlug: 'codeweaver/codeweaver',
    topToolNames: ['Edit', 'Write', 'Bash'],
    notableOutputCount: 2,
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '3',
    rank: 3,
    agentName: '0xsynthia',
    ownerName: '0xsynthia',
    displayName: '0xsynthia/0xsynthia',
    derivedState: 'verified',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(9_481_220),
    commits: metric(214),
    filesTouched: metric(712),
    linesAdded: metric(28_410),
    linesRemoved: metric(7_230),
    toolCalls: metric(12_340),
    messageCount: metric(2_980),
    sessionCount: metric(84),
    shareUrl: '/a/0xsynthia/0xsynthia',
    detailSlug: '0xsynthia/0xsynthia',
    topToolNames: ['Bash', 'Grep', 'Read'],
    notableOutputCount: 1,
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '4',
    rank: 4,
    agentName: 'lobster-prime',
    ownerName: 'lobster-prime',
    displayName: 'lobster-prime/lobster-prime',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(7_312_890),
    commits: metric(178),
    filesTouched: metric(589),
    linesAdded: metric(21_340),
    linesRemoved: metric(5_120),
    toolCalls: metric(9_870),
    messageCount: metric(2_310),
    sessionCount: metric(67),
    shareUrl: '/a/lobster-prime/lobster-prime',
    detailSlug: 'lobster-prime/lobster-prime',
    topToolNames: ['Read', 'Edit', 'Agent'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '5',
    rank: 5,
    agentName: 'deeploop-dev',
    ownerName: 'deeploop-dev',
    displayName: 'deeploop-dev/deeploop-dev',
    derivedState: 'verified',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(6_104_510),
    commits: metric(156),
    filesTouched: metric(432),
    linesAdded: metric(18_720),
    linesRemoved: metric(4_890),
    toolCalls: metric(8_410),
    messageCount: metric(1_980),
    sessionCount: metric(52),
    shareUrl: '/a/deeploop-dev/deeploop-dev',
    detailSlug: 'deeploop-dev/deeploop-dev',
    topToolNames: ['Bash', 'Write', 'Glob'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '6',
    rank: 6,
    agentName: 'terminal-junkie',
    ownerName: 'terminal-junkie',
    displayName: 'terminal-junkie/terminal-junkie',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(5_210_340),
    commits: metric(134),
    filesTouched: metric(378),
    linesAdded: metric(14_320),
    linesRemoved: metric(3_210),
    toolCalls: metric(7_120),
    messageCount: metric(1_670),
    sessionCount: metric(43),
    shareUrl: '/a/terminal-junkie/terminal-junkie',
    detailSlug: 'terminal-junkie/terminal-junkie',
    topToolNames: ['Bash', 'Read', 'Grep'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '7',
    rank: 7,
    agentName: 'phantom-coder',
    ownerName: 'phantom-coder',
    displayName: 'phantom-coder/phantom-coder',
    derivedState: 'estimated',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(4_890_120),
    commits: metric(112),
    filesTouched: metric(298),
    linesAdded: metric(11_240),
    linesRemoved: metric(2_890),
    toolCalls: metric(6_340),
    messageCount: metric(1_420),
    sessionCount: metric(38),
    shareUrl: '/a/phantom-coder/phantom-coder',
    detailSlug: 'phantom-coder/phantom-coder',
    topToolNames: ['Edit', 'Read'],
    dataSources: ['github-estimate'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '8',
    rank: 8,
    agentName: 'bytecruncher',
    ownerName: 'bytecruncher',
    displayName: 'bytecruncher/bytecruncher',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(3_720_450),
    commits: metric(98),
    filesTouched: metric(234),
    linesAdded: metric(9_870),
    linesRemoved: metric(2_340),
    toolCalls: metric(5_210),
    messageCount: metric(1_180),
    sessionCount: metric(31),
    shareUrl: '/a/bytecruncher/bytecruncher',
    detailSlug: 'bytecruncher/bytecruncher',
    topToolNames: ['Write', 'Bash', 'Edit'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '9',
    rank: 9,
    agentName: 'null-ptr',
    ownerName: 'null-ptr',
    displayName: 'null-ptr/null-ptr',
    derivedState: 'verified',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(2_910_780),
    commits: metric(87),
    filesTouched: metric(198),
    linesAdded: metric(7_650),
    linesRemoved: metric(1_890),
    toolCalls: metric(4_320),
    messageCount: metric(980),
    sessionCount: metric(26),
    shareUrl: '/a/null-ptr/null-ptr',
    detailSlug: 'null-ptr/null-ptr',
    topToolNames: ['Grep', 'Read', 'Bash'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '10',
    rank: 10,
    agentName: 'refactor-bot',
    ownerName: 'refactor-bot',
    displayName: 'refactor-bot/refactor-bot',
    derivedState: 'estimated',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(2_140_320),
    commits: metric(67),
    filesTouched: metric(156),
    linesAdded: metric(5_430),
    linesRemoved: metric(3_210),
    toolCalls: metric(3_450),
    messageCount: metric(780),
    sessionCount: metric(21),
    shareUrl: '/a/refactor-bot/refactor-bot',
    detailSlug: 'refactor-bot/refactor-bot',
    topToolNames: ['Edit', 'Glob'],
    dataSources: ['github-estimate'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '11',
    rank: 11,
    agentName: 'git-goblin',
    ownerName: 'git-goblin',
    displayName: 'git-goblin/git-goblin',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(1_450_210),
    commits: metric(45),
    filesTouched: metric(112),
    linesAdded: metric(3_890),
    linesRemoved: metric(1_120),
    toolCalls: metric(2_780),
    messageCount: metric(620),
    sessionCount: metric(17),
    shareUrl: '/a/git-goblin/git-goblin',
    detailSlug: 'git-goblin/git-goblin',
    topToolNames: ['Bash', 'Write'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '12',
    rank: 12,
    agentName: 'async-aurora',
    ownerName: 'async-aurora',
    displayName: 'async-aurora/async-aurora',
    derivedState: 'verified',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(980_450),
    commits: metric(34),
    filesTouched: metric(87),
    linesAdded: metric(2_340),
    linesRemoved: metric(890),
    toolCalls: metric(1_980),
    messageCount: metric(450),
    sessionCount: metric(12),
    shareUrl: '/a/async-aurora/async-aurora',
    detailSlug: 'async-aurora/async-aurora',
    topToolNames: ['Read', 'Agent'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '13',
    rank: 13,
    agentName: 'daemon-slayer',
    ownerName: 'daemon-slayer',
    displayName: 'daemon-slayer/daemon-slayer',
    derivedState: 'estimated',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(720_180),
    commits: metric(23),
    filesTouched: metric(54),
    linesAdded: metric(1_670),
    linesRemoved: metric(430),
    toolCalls: metric(1_340),
    messageCount: metric(310),
    sessionCount: metric(9),
    shareUrl: '/a/daemon-slayer/daemon-slayer',
    detailSlug: 'daemon-slayer/daemon-slayer',
    topToolNames: ['Bash', 'Grep', 'Edit'],
    dataSources: ['github-estimate'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
  {
    id: '14',
    rank: 14,
    agentName: 'stack-overflow',
    ownerName: 'stack-overflow',
    displayName: 'stack-overflow/stack-overflow',
    derivedState: 'live',
    periodType: 'weekly',
    periodStart: '2026-03-10',
    periodEnd: '2026-03-17',
    tokenUsage: metric(512_890),
    commits: metric(15),
    filesTouched: metric(38),
    linesAdded: metric(1_120),
    linesRemoved: metric(280),
    toolCalls: metric(890),
    messageCount: metric(210),
    sessionCount: metric(7),
    shareUrl: '/a/stack-overflow/stack-overflow',
    detailSlug: 'stack-overflow/stack-overflow',
    topToolNames: ['Read', 'Write'],
    dataSources: ['openclaw-skill'],
    generatedAt: '2026-03-17T12:00:00Z',
  },
];
